//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB09AO114_1718Entities1 : DbContext
    {
        public DB09AO114_1718Entities1()
            : base("name=DB09AO114_1718Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAeroplane_HMS03_Team7> tblAeroplane_HMS03_Team7 { get; set; }
        public virtual DbSet<tblBonusMilesRequest_HMS03_Team7> tblBonusMilesRequest_HMS03_Team7 { get; set; }
        public virtual DbSet<tblCustomer_HMS03_Team7> tblCustomer_HMS03_Team7 { get; set; }
        public virtual DbSet<tblEmployee_HMS03_Team7> tblEmployee_HMS03_Team7 { get; set; }
        public virtual DbSet<tblJourney_HMS03_Team7> tblJourney_HMS03_Team7 { get; set; }
        public virtual DbSet<tblLogin_HMS03_Team7> tblLogin_HMS03_Team7 { get; set; }
        public virtual DbSet<tblPassenger_HMS03_Team7> tblPassenger_HMS03_Team7 { get; set; }
        public virtual DbSet<tblPayment_HMS03_Team7> tblPayment_HMS03_Team7 { get; set; }
        public virtual DbSet<tblSchedule_HMS03_Team7> tblSchedule_HMS03_Team7 { get; set; }
        public virtual DbSet<tblSearch_HMS03_Team7> tblSearch_HMS03_Team7 { get; set; }
    }
}
