//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAeroplane_HMS03_Team7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAeroplane_HMS03_Team7()
        {
            this.tblSchedule_HMS03_Team7 = new HashSet<tblSchedule_HMS03_Team7>();
        }
    
        public int PlaneRegistrationID { get; set; }
        public System.DateTime DateOfCommencement { get; set; }
        public System.DateTime DateOdMAnufacturing { get; set; }
        public string AirplaneSeries { get; set; }
        public string Airline { get; set; }
        public int Capacity_Premium { get; set; }
        public int Capacity_FirstClass { get; set; }
        public int Capacity_Economy { get; set; }
        public int TakeOffWeight { get; set; }
        public Nullable<decimal> MaximumDistance { get; set; }
        public string LocationOfPlane { get; set; }
        public Nullable<int> SchedulerID { get; set; }
        public Nullable<System.DateTime> RecentUpdate { get; set; }
        public string ScheduleStatus { get; set; }
    
        public virtual tblEmployee_HMS03_Team7 tblEmployee_HMS03_Team7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSchedule_HMS03_Team7> tblSchedule_HMS03_Team7 { get; set; }
    }
}
