//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBonusMilesRequest_HMS03_Team7
    {
        public int BonusID { get; set; }
        public Nullable<int> JourneyID { get; set; }
        public Nullable<System.DateTime> BonusRequestDate { get; set; }
        public string BonusApprovalStatus { get; set; }
    
        public virtual tblJourney_HMS03_Team7 tblJourney_HMS03_Team7 { get; set; }
    }
}
