//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer_HMS03_Team7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCustomer_HMS03_Team7()
        {
            this.tblJourney_HMS03_Team7 = new HashSet<tblJourney_HMS03_Team7>();
            this.tblPayment_HMS03_Team7 = new HashSet<tblPayment_HMS03_Team7>();
        }
    
        public int CustomerID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string Nationality { get; set; }
        public Nullable<long> MobileNumber { get; set; }
        public Nullable<long> AlternateNumber { get; set; }
        public Nullable<long> PhoneNumber { get; set; }
        public string Email { get; set; }
        public string CompanyName { get; set; }
        public string OfficeAddress { get; set; }
        public Nullable<decimal> BonusMilePoints { get; set; }
    
        public virtual tblLogin_HMS03_Team7 tblLogin_HMS03_Team7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJourney_HMS03_Team7> tblJourney_HMS03_Team7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment_HMS03_Team7> tblPayment_HMS03_Team7 { get; set; }
    }
}
