//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee_HMS03_Team7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee_HMS03_Team7()
        {
            this.tblAeroplane_HMS03_Team7 = new HashSet<tblAeroplane_HMS03_Team7>();
        }
    
        public int EmployeeID { get; set; }
        public Nullable<int> LoginID { get; set; }
        public string Employee_Name { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string Designation { get; set; }
        public string Airlines { get; set; }
        public string Work_location { get; set; }
        public Nullable<long> Contact_Number { get; set; }
        public string EmailID { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAeroplane_HMS03_Team7> tblAeroplane_HMS03_Team7 { get; set; }
        public virtual tblLogin_HMS03_Team7 tblLogin_HMS03_Team7 { get; set; }
    }
}
