//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPassenger_HMS03_Team7
    {
        public int PassengerID { get; set; }
        public Nullable<int> JourneyID { get; set; }
        public string PassengerName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> NoOfBaggages { get; set; }
        public Nullable<decimal> TotalWeightOfBaggages { get; set; }
        public string CheckInStatus { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
    
        public virtual tblJourney_HMS03_Team7 tblJourney_HMS03_Team7 { get; set; }
    }
}
