//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSearch_HMS03_Team7
    {
        public int SearchID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public string Class { get; set; }
        public Nullable<int> NoOfPassengers_Adult { get; set; }
        public Nullable<int> NoOfPassengers_Child { get; set; }
    }
}
