//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SandMax1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSchedule_HMS03_Team7
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSchedule_HMS03_Team7()
        {
            this.tblJourney_HMS03_Team7 = new HashSet<tblJourney_HMS03_Team7>();
            this.tblPayment_HMS03_Team7 = new HashSet<tblPayment_HMS03_Team7>();
        }
    
        public int ScheduleID { get; set; }
        public Nullable<int> PlaneRegistrationID { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
        public System.DateTime Departure { get; set; }
        public System.DateTime Arrival { get; set; }
        public Nullable<decimal> Fare_Premium_Adult { get; set; }
        public Nullable<decimal> Fare_Economy_Adult { get; set; }
        public Nullable<decimal> Fare_Firstclass_Adult { get; set; }
        public Nullable<decimal> Fare_Premium_Child { get; set; }
        public Nullable<decimal> Fare_Firstclass_Child { get; set; }
        public Nullable<decimal> Fare_Economy_Child { get; set; }
        public Nullable<int> Availability_Premium { get; set; }
        public Nullable<int> Availability_Firstclass { get; set; }
        public Nullable<int> Availability_Economy { get; set; }
        public Nullable<decimal> TravelDistance { get; set; }
        public string StatusofFlight { get; set; }
        public string BonusMiles { get; set; }
        public Nullable<decimal> BonusMilesPoints { get; set; }
    
        public virtual tblAeroplane_HMS03_Team7 tblAeroplane_HMS03_Team7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJourney_HMS03_Team7> tblJourney_HMS03_Team7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment_HMS03_Team7> tblPayment_HMS03_Team7 { get; set; }
    }
}
